# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGVinyl', '0002_auto_20170522_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.ManyToManyField(to='OGVinyl.Genre'),
        ),
    ]
