# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGVinyl', '0003_auto_20170525_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='owned',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
