# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGVinyl', '0004_record_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='line_up',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
