# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGVinyl', '0007_auto_20170526_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
