# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGVinyl', '0008_auto_20170526_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
