# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGVinyl', '0010_record_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
